services:
  django:
    image: summarize-information:0.0.1
    build:
      context: ./summarize_information
    ports:
      - "8000:8000"
    environment:
      - AZURE_API_KEY=${AZURE_API_KEY}
      - AZURE_API_ENDPOINT=${AZURE_API_ENDPOINT}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
