version: "3.3"
services:
  nginx:
    build: ./nginx/
    restart: always
    volumes:
      - uwsgi_data:/tmp/uwsgi/
      - web_static:/var/www/summarize_information/assets/:ro
    ports:
      - "80:80"
    depends_on: 
      - django

  django:
    build: ./summarize_information/
    restart: always
    command: >
      sh -c "python manage.py collectstatic --noinput 
      && uwsgi --ini summarize_information.uwsgi.ini"
    volumes:
      - uwsgi_data:/tmp/uwsgi/
      - web_static:/code/static/
      - web_static:/var/www/summarize_information/assets/
    environment:
      - AZURE_API_KEY=${AZURE_API_KEY}
      - AZURE_API_ENDPOINT=${AZURE_API_ENDPOINT}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - AZURE_DB_PW=${AZURE_DB_PW}
  
  prometheus:
    image: prom/prometheus
    volumes: 
      - ./prometheus/:/etc/prometheus/
    ports:
      - "9090:9090"


volumes:
  uwsgi_data:
  web_static: