name: Django CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./summarize_information/requirements.txt

    - name: Set environment variables
      env:
        AZURE_API_KEY: ${{ secrets.AZURE_API_KEY }}
        AZURE_DB:PW: ${{ secrets.AZURE_DB_PW }}
        DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
      run: |
        export AZURE_API_KEY=$AZURE_API_KEY
        export AZURE_DB_PW=$AZURE_DB_PW
        export DJANGO_SECRET_KEY=$DJANGO_SECRET_KEY

    - name: Run tests
      run: |
        python ./summarize_information/manage.py test core
